name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
    - name: Publish the Docker image
    - with:
        username: ${{ secrets.DOCKER_USERNAME}}
        passowrd: ${{ secrets.DOCKER_PASSWORD}}
        repository: jbesclapez/biglybt-3.2.0.0-extreme
        tags: latest, ${{ github.run_number}}
     
